<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="1" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="135562" started-at="2020-08-07T03:40:46Z" finished-at="2020-08-07T03:43:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="135562" started-at="2020-08-07T03:40:46Z" finished-at="2020-08-07T03:43:01Z">
      <class name="com.product.qa.testcases.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="setUp" is-config="true" duration-ms="37411" started-at="2020-08-07T09:10:46Z" finished-at="2020-08-07T09:11:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="LoginPageTitletest()[pri:1, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="LoginPageTitletest" duration-ms="5039" started-at="2020-08-07T09:11:23Z" finished-at="2020-08-07T09:11:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MZ Training Portal - Login] but found [MZ Training Portal]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MZ Training Portal - Login] but found [MZ Training Portal]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.product.qa.testcases.LoginTest.LoginPageTitletest(LoginTest.java:36)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginPageTitletest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="tearDown" is-config="true" duration-ms="608" started-at="2020-08-07T09:11:28Z" finished-at="2020-08-07T09:11:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="setUp" is-config="true" duration-ms="19633" started-at="2020-08-07T09:11:29Z" finished-at="2020-08-07T09:11:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="MzLogoImagetest()[pri:2, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="MzLogoImagetest" duration-ms="5154" started-at="2020-08-07T09:11:49Z" finished-at="2020-08-07T09:11:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at com.product.qa.testcases.LoginTest.MzLogoImagetest(LoginTest.java:42)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MzLogoImagetest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="tearDown" is-config="true" duration-ms="649" started-at="2020-08-07T09:11:54Z" finished-at="2020-08-07T09:11:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="setUp" is-config="true" duration-ms="32889" started-at="2020-08-07T09:11:54Z" finished-at="2020-08-07T09:12:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="ValidateLogin()[pri:3, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="ValidateLogin" duration-ms="32869" started-at="2020-08-07T09:12:27Z" finished-at="2020-08-07T09:13:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.product.qa.testcases.LoginTest@63753b6d]" name="tearDown" is-config="true" duration-ms="1242" started-at="2020-08-07T09:13:00Z" finished-at="2020-08-07T09:13:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.product.qa.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
